### ISSUE TITLE
request for RCNN image feature

### ISSUE THREAD

**Issue by congjinlingdaoganling** [guoyang9/Relation-Fact-Detector#1]
Could i have your the prepocessed RCNN image feature of Visual Genome? Thank U!

**Comment by guoyang9** [comment]
Please provide me with your email, the feature file is too big.

**Comment by congjinlingdaoganling** [comment]
Thank you for your reply，my email adress is 714753195@qq.com。




best your wishes！
Zhou


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yangyang Guo"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月31日(星期四) 上午8:46
收件人:&nbsp;"guoyang9/Relation-Fact-Detector"<Relation-Fact-Detector@noreply.github.com&gt;;
抄送:&nbsp;"周涛"<714753195@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [guoyang9/Relation-Fact-Detector] request for RCNN image feature (#1)




Please provide me with your email, the feature file is too big.
