### ISSUE TITLE
Hello！

### ISSUE THREAD

**Issue by sysugargantua** [guoyang9/Relation-Fact-Detector#3]
while training the preprocess image feature, i met something wrong like that,
![Snipaste_2019-12-29_22-22-31](https://user-images.githubusercontent.com/57032109/71558044-bd1e7f00-2a89-11ea-93d4-7e16699d1833.png)
and i've tried many ways to solve it, but failed.

So, if possible, could you please give me the genome-trainval.h5  file, which is not the .tsv file?
Or may you've solved this problem?
Many thanks!!!

**Comment by sysugargantua** [comment]
My email address is 1365457082@qq.com.  
Really appreciate your help！！

By the way, in the first step:   (python image.py)
I'm confused if this is the correct image feature of Visual Genome:  
![image](https://user-images.githubusercontent.com/57032109/71559665-f233cd00-2a9b-11ea-9805-a1f3c4ba5c8d.png)

**Comment by guoyang9** [comment]
As I said, the h5 file is too big to be uploaded.
There might be something wrong with the tsv file. Allow me a few days to re-extract the visual genome features.

**Comment by sysugargantua** [comment]
Thank you so much for your help!!!
I'e successfully trained the image feature, but there is another question:&nbsp;
I studied the whole model but I haven't found the code which is to train VG.h5.
Could you tell me how to get the VG.h5 file?
So sorry to bother you


&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
