### ISSUE TITLE
Hello, bro!!

### ISSUE THREAD

**Issue by Giasburn** [guoyang9/Relation-Fact-Detector#4]
Thank you so much for your efforts!
I'm confused about this part: 
![image](https://user-images.githubusercontent.com/47476295/72574514-4f38db00-3904-11ea-9fc7-f2c01479adf5.png)
how to get the VG.h5 file? seems this project dont have code to train the VG.h5 file?

**Comment by guoyang9** [comment]
I would recommend anyone who use this repo do read the README first.
